export const projects = [
  {
    id: 8,
    inProgress: true,
    name: "OccasioNex",
    description: "Event Management Software",
    overview:
      "OccasioNex is an intuitive event management application designed to simplify the planning process for any occasion. From weddings and parties to corporate events, OccasioNex offers comprehensive tools for organizing guest lists, scheduling, budgeting, and more.",
    logo: "./projects/buyMeACoffee.png",
    thumbnail: "./testThumbnail.png",
    techStack: ["NextJS", "React", "MongoDB", "Tailwind CSS"],
    url: "https://github.com/mohsin-khan07/OccasioNex",
    repoLink: "https://github.com/mohsin-khan07/OccasioNex",
  },
  {
    id: 7,
    inProgress: true,
    name: "Alpine Haven",
    description: "Hotel Management Application",
    overview:
      "Alpine Haven is your ultimate companion for managing a hotel with ease and efficiency. From seamless booking and check-in experiences to personalized guest services, Alpine Haven empowers you to create unforgettable getaways for your guests while streamlining your operations.",
    logo: "./projects/buyMeACoffee.png",
    thumbnail: "./testThumbnail.png",
    techStack: ["React", "React Query", "Supabase", "Styled Components"],
    url: "https://github.com/mohsin-khan07/AlpineHaven",
    repoLink: "https://github.com/mohsin-khan07/AlpineHaven",
  },
  {
    id: 6,
    inProgress: false,
    name: "Yum Yield",
    description: "Recipe Finder Web App",
    overview:
      "Yum Yield is a recipe finder application designed to help users discover and explore a wide variety of recipes from around the world.",
    logo: "./projects/buyMeACoffee.png",
    thumbnail: "./testThumbnail.png",
    techStack: ["HTML", "JavaScript", "Sass"],
    url: "https://yumyield.vercel.app",
    repoLink: "https://github.com/mohsin-khan07/YumYield",
  },
  {
    id: 5,
    inProgress: false,
    name: "Buy Me A Coffee",
    description: "Decentralized Crowdfunding Platform",
    overview:
      "Buy Me A Coffee is a decentralized app similar to buy me a coffee website. In this anyone can send the owner some Ethereum.",
    logo: "./projects/buyMeACoffee.png",
    thumbnail: "./testThumbnail.png",
    techStack: ["Solidity", "React", "Tailwind CSS", "Ethers.js", "Hardhat"],
    url: "https://buymeacoffeedapp.vercel.app",
    repoLink: "https://github.com/mohsin-khan07/BuyMeACoffee",
  },
  {
    id: 4,
    inProgress: false,
    name: "Coin Guardian",
    description: "Decentralized Escrow Application",
    overview:
      "A decentralized escrow smart contract application. A secure gateway to transparent transactions in the crypto world.",
    logo: "./projects/coinGuardian.png",
    thumbnail: "./testThumbnail.png",
    techStack: ["Solidity", "React", "Ethers.js", "Hardhat"],
    url: "https://coinguardian.netlify.app",
    repoLink: "https://github.com/mohsin-khan07/coin-guardian",
  },
  {
    id: 3,
    inProgress: false,
    name: "NFT Gaze",
    description: "NFT Indexer App",
    overview:
      "NFT Gaze is your go-to app for effortlessly tracking your NFT holdings on the Ethereum blockchain.",
    logo: "./projects/nftGaze.png",
    thumbnail: "./testThumbnail.png",
    techStack: ["React", "Alchemy SDK", "Ethers.js"],
    url: "https://nftgaze.netlify.app",
    repoLink: "https://github.com/mohsin-khan07/NFT-Gaze",
  },
  {
    id: 2,
    inProgress: false,
    name: "Token Trove",
    description: "ERC20 Tokens Indexer App",
    overview:
      "Token Trove is your go-to app for effortlessly tracking your ERC20 tokens holdings on the Ethereum blockchain.",
    logo: "./projects/tokenTrove.png",
    thumbnail: "./testThumbnail.png",
    techStack: ["React", "Alchemy SDK", "Ethers.js"],
    url: "https://tokentrove.netlify.app",
    repoLink: "https://github.com/mohsin-khan07/token-trove",
  },
  {
    id: 1,
    inProgress: false,
    name: "Chain Surge",
    description: "Ethereum Block Explorer",
    overview:
      "An Ethereum block explorer for seamless navigation through blocks, transactions, and addresses, delivering real-time insights into the network's activity.",
    logo: "./projects/chainSurge.png",
    thumbnail: "./testThumbnail.png",
    techStack: ["React", "Alchemy SDK", "Ethers.js", "CoinCap API"],
    url: "https://chainsurge.netlify.app",
    repoLink: "https://github.com/mohsin-khan07/chain-surge",
  },
];
