export const projects = [
  {
    id: 8,
    urlName: "occasionex",
    inProgress: true,
    name: "OccasioNex",
    description: "Event Management Software",
    overview:
      "OccasioNex is an intuitive event management application designed to simplify the planning process for any occasion. From weddings and parties to corporate events, OccasioNex offers comprehensive tools for organizing guest lists, scheduling, budgeting, and more.",
    logo: "/projects/buyMeACoffee.png",
    thumbnail: "/projects/comingsoon.png",
    keyFeatures: ["", ""],
    techStack: ["NextJS", "React", "MongoDB", "Tailwind CSS"],
    url: "https://github.com/mohsin-khan07/OccasioNex",
    repoLink: "https://github.com/mohsin-khan07/OccasioNex",
  },
  {
    id: 7,
    urlName: "alpine-haven",
    inProgress: true,
    name: "Alpine Haven",
    description: "Hotel Management Application",
    overview:
      "Alpine Haven is your ultimate companion for managing a hotel with ease and efficiency. From seamless booking and check-in experiences to personalized guest services, Alpine Haven empowers you to create unforgettable getaways for your guests while streamlining your operations.",
    logo: "/projects/buyMeACoffee.png",
    thumbnail: "/projects/comingsoon.png",
    keyFeatures: ["", ""],
    techStack: ["React", "React Query", "Supabase", "Styled Components"],
    url: "https://github.com/mohsin-khan07/AlpineHaven",
    repoLink: "https://github.com/mohsin-khan07/AlpineHaven",
  },
  {
    id: 6,
    urlName: "yum-yield",
    inProgress: false,
    name: "Yum Yield",
    description: "Recipe Finder Web App",
    overview:
      "Yum Yield is a recipe finder application designed to help users discover and explore a wide variety of recipes from around the world.",
    logo: "/projects/buyMeACoffee.png",
    thumbnail: "/projects/yumyield-tb.png",
    keyFeatures: [
      "Recipe Search: Users can search for recipes based on various criteria such as ingredients, cuisine type, dietary restrictions, and cooking time.",
      "Recipe Details: Each recipe page provides detailed instructions, including ingredients, preparation steps, cooking time, and dynamic serving size.",
      "Recipe Serving Adjustment: Users can dynamically adjust the serving size of recipes to accommodate different serving requirements or occasions.",
      "Bookmarking: Users can save their favorite recipes for quick access later.",
    ],
    techStack: ["HTML", "JavaScript", "Sass"],
    url: "https://yumyield.vercel.app",
    repoLink: "https://github.com/mohsin-khan07/YumYield",
  },
  {
    id: 5,
    urlName: "buy-me-a-coffee",
    inProgress: false,
    name: "Buy Me A Coffee",
    description: "Decentralized Crowdfunding Platform",
    overview:
      "Buy Me A Coffee is a decentralized app similar to buy me a coffee website. In this anyone can send the owner some Ethereum.",
    logo: "/projects/buyMeACoffee.png",
    thumbnail: "/projects/buymeacoffee-tb.png",
    keyFeatures: ["", ""],
    techStack: ["Solidity", "React", "Tailwind CSS", "Ethers.js", "Hardhat"],
    url: "https://buymeacoffeedapp.vercel.app",
    repoLink: "https://github.com/mohsin-khan07/BuyMeACoffee",
  },
  {
    id: 4,
    urlName: "coin-guardian",
    inProgress: false,
    name: "Coin Guardian",
    description: "Decentralized Escrow Application",
    overview:
      "A decentralized escrow smart contract application. A secure gateway to transparent transactions in the crypto world.",
    logo: "/projects/coinGuardian.png",
    thumbnail: "/projects/coinguardian-tb.png",
    keyFeatures: ["", ""],
    techStack: ["Solidity", "React", "Ethers.js", "Hardhat"],
    url: "https://coinguardian.netlify.app",
    repoLink: "https://github.com/mohsin-khan07/CoinGuardian",
  },
  {
    id: 3,
    urlName: "nft-gaze",
    inProgress: false,
    name: "NFT Gaze",
    description: "NFT Indexer App",
    overview:
      "NFT Gaze is your go-to app for effortlessly tracking your NFT holdings on the Ethereum blockchain.",
    logo: "/projects/nftGaze.png",
    thumbnail: "/testThumbnail.png",
    keyFeatures: ["", ""],
    techStack: ["React", "Alchemy SDK", "Ethers.js"],
    url: "https://nftgaze.netlify.app",
    repoLink: "https://github.com/mohsin-khan07/NFT-Gaze",
  },
  {
    id: 2,
    urlName: "token-trove",
    inProgress: false,
    name: "Token Trove",
    description: "ERC20 Tokens Indexer App",
    overview:
      "Token Trove is your go-to app for effortlessly tracking your ERC20 tokens holdings on the Ethereum blockchain.",
    logo: "/projects/tokenTrove.png",
    thumbnail: "/projects/tokentrove-tb.png",
    keyFeatures: [
      "Wallet Connection: Seamlessly connect your Ethereum wallet to instantly view and manage all your tokens in one place.",
      "Real-time Updates: Stay informed with up-to-the-minute token balances and market values, ensuring you never miss a beat in the dynamic world of cryptocurrency.",
      "Address Lookup: Curious about token holdings in a specific address? Simply enter the Ethereum address, and Token Trove will reveal the comprehensive token portfolio associated with it.",
      "User-Friendly Interface: Navigating through your token portfolio has never been smoother. Token Trove boasts an intuitive design, making it accessible for users of all levels.",
    ],
    techStack: ["React", "Alchemy SDK", "Ethers.js"],
    url: "https://tokentrove.netlify.app",
    repoLink: "https://github.com/mohsin-khan07/TokenTrove",
  },
  {
    id: 1,
    urlName: "chain-surge",
    inProgress: false,
    name: "Chain Surge",
    description: "Ethereum Block Explorer",
    overview:
      "An Ethereum block explorer for seamless navigation through blocks, transactions, and addresses, delivering real-time insights into the network's activity.",
    logo: "/projects/chainSurge.png",
    thumbnail: "/projects/chainsurge-tb.png",
    keyFeatures: ["", ""],
    techStack: ["React", "Alchemy SDK", "Ethers.js", "CoinCap API"],
    url: "https://chainsurge.netlify.app",
    repoLink: "https://github.com/mohsin-khan07/ChainSurge",
  },
];
